### ISSUE TITLE
[🐞]Zod issue with 1.17.1 zod and drizzle-zod

### ISSUE THREAD

**Issue by artecoop** [QwikDev/qwik#8096]
### Which component is affected?

Qwik City (routing)

### Describe the bug

After updating to 1.17.1 the zod integration breaks when using drizzle-zod, in particular "createInsertSchema".
The error is
`Internal server error: keyValidator._parse is not a function`

using z.object does not have this problem.

Downgrading to 1.17.0 restore all the correct functionalities

### Reproduction

--

### System Info

```shell
System:
    OS: macOS 26.0.1
    CPU: (8) arm64 Apple M1
    Memory: 3.58 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.21.0 - /usr/local/bin/node
    npm: 10.9.4 - /usr/local/bin/npm
    pnpm: 10.19.0 - /Users/vfornito/Library/pnpm/pnpm
  Browsers:
    Chrome: 141.0.7390.123
    Safari: 26.0.1
  npmPackages:
    @builder.io/qwik: 1.17.1 => 1.17.1 
    @builder.io/qwik-city: 1.17.1 => 1.17.1 
    typescript: 5.9.3 => 5.9.3 
    undici: * => 7.16.0 
    vite: 7.1.12 => 7.1.12
```
