### ISSUE TITLE
[🐞] V2 migration tool should also update "moduleResolution" to "Bundler" in tsconfig.json

### ISSUE THREAD

**Issue by jakovljevic-mladen** [QwikDev/qwik#7130]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I installed qwik application in version 1.2.10 [when the default](https://github.com/QwikDev/qwik/blob/v1.2.10/starters/apps/base/tsconfig.json#L12) `"moduleResolution"` in `tsconfig.json` value was set to `"node"`. After migrating to V2 alpha, this does not work producing an error on any line that has `import ... from '@qwik.dev/core';` where an error says:

```
TS2307: Cannot find module @qwik.dev/ core or its corresponding type declarations.
There are types at
.../node_modules/@qwik.dev/core/public.d.ts
, but this result could not be resolved under your current moduleResolution setting. Consider updating to node16, nodenext, or bundler
```

Updating `moduleResolution` value to `Bundler` fixes the problem, so I believe V2 migration tool should consider updating `moduleResolution` field to `Bundler` among other things it does.

### Reproduction

https://qwik.new/

### Steps to reproduce

Not really sure, but this should be correct:

- Install Qwik version 1.2.10.
- Update to Qwik 1.11.0 manually (make sure `moduleResolution` is set to `node` in `tsconfig.json`.
- Run `qwik migrate-v2`.
- Open any file that has something like this: `import ... from '@qwik.dev/core';`.
- Error is present below `'@qwik.dev/core'`.

### System Info

```shell
V2
```

**Comment by wmertens** [comment]
Hmm, I think it's not safe to just change it, but maybe it could just ask for it @dmitry-stepanenko ?

In any case that's a bug in how we package qwik, it should still work with `node` resolution :(

**Comment by jakovljevic-mladen** [comment]
>In any case that's a bug in how we package qwik, it should still work with node resolution :(

Shall I update the ticket then?

**Comment by shairez** [comment]
actually solved the root bug in https://github.com/QwikDev/qwik/pull/7159

@dmitry-stepanenko I'll comment out the "bundler' logic for now (just in case, until we'll gather more feedback if this can be turned on)
But now that the root cause is fixed, it should "just work"™ 🙂
