### ISSUE TITLE
[🐞]Unable to contribute to project from Windows Operating System (OS)

### ISSUE THREAD

**Issue by Shane-Donlon** [QwikDev/qwik#7175]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hey everyone,
Logging this for team level visibility.

I have added the recap to the top as this is probably a small project.

I am more than happy to contribute with testing &/ code changes.
But would like to discuss this with a team-member so that we can run some testing across Operating Systems before committing to the changes.

Also don't mind jumping on some Discord calls to screenshare / troubleshoot etc..

## Recap

- [ ] Issue 1:  Dockerfile to be udated `FROM cimg/rust:1.74-node`
- [x] Issue 2: PNPM Permission Denied error
- [x] Issue 3: Builds are failing resolved in https://github.com/QwikDev/qwik/pull/7200
- [x] Issue 4: Package.json files to be updated.

## Issue Description.

It seems that I am unable to contribute to the project from Windows OS .

There are few issues I have encountered along the way reading the instructions

Issue 1: 
I used the CLI just to easily catch the error to copy paste, but this is also an issue with the devcontainer extension.

```terminal
@devcontainers/cli 0.72.0. Node.js v22.11.0. win32 10.0.22631 x64.
```
```terminal

112.3 error: failed to compile `wasm-pack v0.13.1`, intermediate artifacts can be found at `/tmp/cargo-install2iOZDd`.
112.3 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
112.3
112.3 Caused by:
112.3   package `clap_derive v4.5.18` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0
```

This is resolved by updating the Dockerfile in .devcontainer to 
```dockerifle 
FROM cimg/rust:1.74-node
```

Issue 2:
After updating to 1.74 and running command `devcontainer up --workspace-folder .`
container in Docker does start 

![confirmation image of docker](https://github.com/user-attachments/assets/a3bf5751-f361-459b-921e-bb161935f9d1)

Then I run into the below error for PNPM
```terminal 
Downloading @img/sharp-libvips-linuxmusl-x64@1.0.4: 7.20 MB/7.20 MB, done
 ERR_PNPM_EACCES  EACCES: permission denied, rename '/workspaces/qwik/node_modules/.pnpm/micromark-factory-space@2.0.0/node_modules/micromark-factory-space_tmp_59' -> '/workspaces/qwik/node_modules/.pnpm/micromark-factory-space@2.0.0/node_modules/micromark-factory-space'
Progress: resolved 1949, reused 0, downloaded 404, added 41
```
```json
{"outcome":"error","message":"Command failed: /bin/sh -c corepack prepare & pnpm install","description":"The updateContentCommand in the devcontainer.json failed.","containerId":"container id details here"}
```

solution commands in terminal
`corepack prepare pnpm@9.15.0 --activate`
`pnpm install`

```terminal
. prepare$ simple-git-hooks
│ [INFO] Successfully set the pre-commit with command: pnpm pretty-quick --staged
│ [INFO] Successfully set all git hooks
└─ Done in 363ms
Done in 1m 13.7s
```
Issue 3:
After running `pnpm build.local` OR after running `pnpm build.full`
Same error for both commands.
```
⚛️  supabase-auth-helpers-qwik
packages/docs/src/repl/worker/repl-dependencies.ts:51:3 - error TS2740: Type '{ isServer: true; isBrowser: false; isDev: false; }' is missing the following properties from type 'typeof import("{other locatino stuff}qwik/packages/qwik/dist/core")': getLocale, useServerData, withLocale, $, and 86 more.

51   self.qwikBuild = {
     ~~~~~~~~~~~~~~

```
Error message:

```terminal
Found 1 error in packages/docs/src/repl/worker/repl-dependencies.ts:51
❌ Error: Command failed with exit code 2: tsc -p packages\docs\tsconfig.json
```

Issue 4
the below commands don't work on windows due to "&&" and may need to be moved to concurrently (already in devDependencies) 

    "docs.dev": "cd packages/docs && pnpm build.repl-sw && pnpm dev",

`pnpm docs.dev` command

```terminal 
> qwik-monorepo@0.0.0-read-qwik-package-json docs.dev {location of stuff}\qwik
> cd packages/docs && pnpm build.repl-sw && pnpm dev

cd: no such file or directory: packages/docs
```
Ignore the error. This exists but if I run 
```json
    "docs.dev": "concurrently \"cd packages/docs && pnpm build.repl-sw\" \"cd packages/docs && pnpm dev\""
``` 
 this seems to work, but  I run into another problem with the package/docs package.json as it has other script that use the same syntax

```terminal
[1] === Running 'pnpm run build.local' to generate missing imports for the docs ===
[1]
[1] Failed to build local packages
[1]  ELIFECYCLE  Command failed with exit code 1.
[1] cd packages/docs && pnpm dev exited with code 1
[0] transforming...
[0] ✓ 10 modules transformed.


[0] ✓ built in 1.50s
[0] cd packages/docs && pnpm build.repl-sw exited with code 0
 ELIFECYCLE  Command failed with exit code 1.
```
general confirmation 

- Visual Studio 2002 is installed
- Visual Studio Build Tools 2002 is installed
- Make sure Rust is installed.
- Install  wasm-pack with cargo install wasm-pack .
- Node version >= 18.
- Make sure you have PNPM installed.
- This is the main branch, also issue for V2 branch.

![visual studio and build tools installed confirmation](https://github.com/user-attachments/assets/dc7332ae-34a5-4f2f-a9ce-f1616c6b9e7a)

### Reproduction

this cannot be blank to log the issue

### Steps to reproduce

this cannot be blank to log the issue, see above.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 1.09 GB / 7.74 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.14.2 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.1.38 - ~\AppData\Roaming\npm\bun.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @builder.io/partytown: 0.10.2 => 0.10.2
    @builder.io/qwik: workspace:^ => 1.11.0
    @builder.io/qwik-city: workspace:^ => 1.11.0
    typescript: 5.4.5 => 5.4.5
    undici: * => 6.6.2
    vite: 5.3.5 => 5.3.5
```

**Comment by Shane-Donlon** [comment]
Root package.json 

```json
"docs.dev": "concurrently \"cd packages/docs && pnpm build.repl-sw\" \"cd packages/docs && pnpm dev\"",
```

and packages/docs package.json  
```json
  "dev": "concurrently \"tsx check-qwik-build.ts\" \"vite --mode ssr --open\"",
```

Allows me to get the docs running in localhost
![confirmation of page opening in localhost](https://github.com/user-attachments/assets/17cef11d-8cc7-4368-b381-c7c3701f6c93)

**Comment by gioboa** [comment]
Thanks @Shane-Donlon 
I'm so sorry about that, would you like to help us and drop a PR to fill this gap? Thanks in advance

**Comment by Shane-Donlon** [comment]
Resolved with PR 7388.
`pnpm docs.dev` script now runs from root package.json location on Windows.
